name: string_calculator
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  test: ^1.25.15

dev_dependencies:
  lints: ^5.0.0
